### ISSUE TITLE
Admin Routes: CRUD on CouchDB Microservice

### ISSUE THREAD

**Issue by Ryan-Gordon** [Ryan-Gordon/Final-Year-Project-API#5]
Admins for the app should be able to perform full CRUD capabilities on the db provided they supply valid admin credentials.

- [] Ryan-Gordon/Final-Year-Project-API#1 
- [] Ryan-Gordon/Final-Year-Project-API#4
- [] Ryan-Gordon/Final-Year-Project-API#3 
- [] Ryan-Gordon/Final-Year-Project-API#2

**Comment by Ryan-Gordon** [comment]
All dependant tasks done. Closing for now
